[package]
name = "tutorial3-pipeline"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
winit = "0.20"
glsl-to-spirv = "0.1"
cgmath = "0.17"
wgpu = "0.5.0"
futures = "0.3.4"

[[bin]]
name = "tutorial3-pipeline"
path = "src/main.rs"

[[bin]]
name = "tutorial3-challenge"
path = "src/challenge.rs"