[package]
name = "tutorial10-lighting"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"
env_logger = "0.8"
pollster = "0.2"
image = "0.23"
log = "0.4"
tobj = "3.0"
wgpu = { version = "0.8", features = ["cross"]}
winit = "0.25"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[[bin]]
name = "tutorial10-lighting"
path = "src/main.rs"
