[package]
name = "tutorial6-uniforms"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
winit = "0.20.0-alpha4"
glsl-to-spirv = "0.1"
wgpu = "0.4"
cgmath = "0.17"

[[bin]]
name = "tutorial6-uniforms"
path = "src/main.rs"


[[bin]]
name = "tutorial6-challenge"
path = "src/challenge.rs"