[package]
name = "windowless"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
raw-window-handle = "0.3"
winit = "0.24"
shaderc = "0.7"
cgmath = "0.18"
wgpu = "0.8"
futures = "0.3.4"

[[bin]]
name = "windowless"
path = "src/main.rs"
