[package]
name = "tutorial11-normals"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.22"
shaderc = "0.6"
# cgmath = "0.17"
failure = "0.1"
tobj = "1"
bytemuck = "1.2"
futures = "0.3.4"
wgpu = "0.5.0"

[dependencies.cgmath]
version = "0.17"
features = ["swizzle"]

[[bin]]
name = "tutorial11-normals"
path = "src/main.rs"


# [[bin]]
# name = "tutorial10-challenge"
# path = "src/challenge.rs"