[package]
name = "lost-window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
wgpu = "0.15"
winit = "0.27"
pollster = "0.2"