[package]
name = "tutorial1-window"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "tutorial1-window"
path = "src/main.rs"

[dependencies]
image = "0.22"
winit = "0.20"
glsl-to-spirv = "0.1"
cgmath = "0.17"
wgpu = "0.5.0"
